//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dem
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public int id { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> dateSmen { get; set; }
        public Nullable<int> zayavka { get; set; }
    
        public virtual Zayavki Zayavki { get; set; }
    }
}
