//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class zayavkiEntities : DbContext
    {
        public zayavkiEntities()
            : base("name=zayavkiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public static zayavkiEntities context;
        public static zayavkiEntities GetContext()
        {
            if(context==null)
                context = new zayavkiEntities();
            return context;
        }
    
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<history> history { get; set; }
        public virtual DbSet<master> master { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<typeEquipment> typeEquipment { get; set; }
        public virtual DbSet<Zayavki> Zayavki { get; set; }
    }
}
