//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zayavki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zayavki()
        {
            this.history = new HashSet<history>();
        }
    
        public int id { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> client { get; set; }
        public Nullable<int> typeEquip { get; set; }
        public Nullable<System.DateTime> dateOform { get; set; }
        public Nullable<System.DateTime> dateVip { get; set; }
        public string model { get; set; }
        public Nullable<int> master { get; set; }
    
        public virtual client client1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<history> history { get; set; }
        public virtual master master1 { get; set; }
        public virtual status status1 { get; set; }
        public virtual status status2 { get; set; }
        public virtual typeEquipment typeEquipment { get; set; }
    }
}
